import {
  type Article,
  type AlertRecord,
  type DistrictRisk,
  type EntityCooccurrenceData,
  type Keyword,
  type Report,
  type Source,
  type TVChannel,
  type SentimentTrendPoint,
  type TopicDistributionItem,
  type SourceVolumeItem,
  type Severity,
  type User,
} from "@/types";

const now = new Date();
const iso = now.toISOString();

export const MOCK_ARTICLES: Article[] = [
  {
    id: "art-1",
    title: "गोरखपुर में विकास कार्यों की तेज़ रफ़्तार, मुख्यमंत्री ने किया निरीक्षण",
    content:
      "गोरखपुर में सड़क, बिजली और स्वास्थ्य से जुड़े कई प्रोजेक्ट्स का निरीक्षण किया गया। विपक्ष ने कुछ योजनाओं की गति पर सवाल उठाए हैं।",
    summary_english:
      "CM visits Gorakhpur to review development projects. Multiple infrastructure works are ongoing with mixed public response.",
    summary_hindi:
      "मुख्यमंत्री ने गोरखपुर में विकास कार्यों की समीक्षा की। कई परियोजनाएँ तेज़ी से चल रही हैं, कुछ पर स्थानीय लोगों ने सवाल भी उठाए।",
    url: "https://example.com/article/gorakhpur-development",
    source_name: "Dainik Jagran Gorakhpur",
    source_type: "print",
    published_at: iso,
    ingested_at: iso,
    language: "hi",
    sentiment: "positive",
    sentiment_score: 78,
    severity: "MEDIUM",
    districts_mentioned: ["Gorakhpur"],
    persons_named: ["Yogi Adityanath"],
    schemes_referenced: ["PM Awas Yojana"],
    departments_mentioned: [],
    topics: ["development", "infrastructure"],
    is_law_order: false,
    risk_flag: false,
    swot_tag: "strength",
    misinformation_signal: false,
    alerted: false,
    youtube_video_id: null,
    youtube_timestamp: null,
    keywords_matched: ["गोरखपुर", "विकास"],
  },
  {
    id: "art-2",
    title: "कानपुर में law & order पर सवाल, विपक्ष ने जताई चिंता",
    content:
      "कानपुर में हाल ही में हुई घटनाओं को लेकर विपक्ष ने कानून व्यवस्था को लेकर सरकार पर निशाना साधा है।",
    summary_english:
      "Opposition questions law & order situation in Kanpur after recent incidents.",
    summary_hindi:
      "हालिया घटनाओं के बाद विपक्ष ने कानपुर में कानून व्यवस्था की स्थिति पर चिंता जताई है।",
    url: "https://example.com/article/kanpur-law-order",
    source_name: "ABP Ganga",
    source_type: "tv",
    published_at: iso,
    ingested_at: iso,
    language: "hi",
    sentiment: "negative",
    sentiment_score: 32,
    severity: "CRITICAL",
    districts_mentioned: ["Kanpur Nagar"],
    persons_named: ["Opposition leaders"],
    schemes_referenced: [],
    departments_mentioned: [],
    topics: ["law-order", "politics"],
    is_law_order: true,
    risk_flag: true,
    swot_tag: "weakness",
    misinformation_signal: false,
    alerted: true,
    youtube_video_id: "dQw4w9WgXcQ",
    youtube_timestamp: 60,
    keywords_matched: ["कानपुर", "law & order"],
  },
  {
    id: "art-3",
    title: "लखनऊ: स्वास्थ्य योजनाओं का विस्तार, 50 नई डिस्पेंसरी खुलेंगी",
    content:
      "मुख्यमंत्री ने घोषणा की कि राजधानी लखनऊ सहित कई जिलों में स्वास्थ्य सुविधाओं का विस्तार किया जाएगा।",
    summary_english:
      "CM announces expansion of health schemes; 50 new dispensaries to open in Lucknow and nearby districts.",
    summary_hindi:
      "मुख्यमंत्री ने लखनऊ और आसपास के जिलों में 50 नई डिस्पेंसरी खोलने की घोषणा की।",
    url: "https://example.com/article/lucknow-health",
    source_name: "Amar Ujala Lucknow",
    source_type: "print",
    published_at: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    ingested_at: iso,
    language: "hi",
    sentiment: "positive",
    sentiment_score: 82,
    severity: null,
    districts_mentioned: ["Lucknow", "Barabanki"],
    persons_named: ["Yogi Adityanath"],
    schemes_referenced: ["Ayushman Bharat"],
    departments_mentioned: [],
    topics: ["health", "governance", "development"],
    is_law_order: false,
    risk_flag: false,
    swot_tag: "opportunity",
    misinformation_signal: false,
    alerted: false,
    youtube_video_id: null,
    youtube_timestamp: null,
    keywords_matched: ["लखनऊ", "स्वास्थ्य"],
  },
  {
    id: "art-4",
    title: "वाराणसी में सड़क दुर्घटना: तीन घायल, यातायात रुका",
    content:
      "वाराणसी के अस्सी इलाके में सड़क दुर्घटना में तीन लोग घायल हुए। पुलिस ने मामला दर्ज किया।",
    summary_english:
      "Road accident in Varanasi leaves three injured; traffic disrupted. Police registered case.",
    summary_hindi:
      "वाराणसी में सड़क दुर्घटना में तीन घायल, पुलिस जाँच में जुटी।",
    url: "https://example.com/article/varanasi-accident",
    source_name: "Dainik Bhaskar Varanasi",
    source_type: "online",
    published_at: new Date(now.getTime() - 90 * 60 * 1000).toISOString(),
    ingested_at: iso,
    language: "hi",
    sentiment: "neutral",
    sentiment_score: 52,
    severity: "LOW",
    districts_mentioned: ["Varanasi"],
    persons_named: [],
    schemes_referenced: [],
    departments_mentioned: [],
    topics: ["accident", "traffic"],
    is_law_order: false,
    risk_flag: false,
    swot_tag: null,
    misinformation_signal: false,
    alerted: false,
    youtube_video_id: null,
    youtube_timestamp: null,
    keywords_matched: ["वाराणसी"],
  },
  {
    id: "art-5",
    title: "प्रयागराज में नकली नोट मामला: एक गिरफ्तार",
    content:
      "प्रयागराज पुलिस ने नकली नोट बनाने के आरोप में एक व्यक्ति को गिरफ्तार किया।",
    summary_english:
      "Prayagraj police arrest one in fake currency case. Investigation ongoing.",
    summary_hindi:
      "प्रयागराज में नकली नोट मामले में एक गिरफ्तार, जाँच जारी।",
    url: "https://example.com/article/prayagraj-fake-notes",
    source_name: "News18 UP",
    source_type: "tv",
    published_at: new Date(now.getTime() - 5 * 60 * 60 * 1000).toISOString(),
    ingested_at: iso,
    language: "hi",
    sentiment: "negative",
    sentiment_score: 28,
    severity: "HIGH",
    districts_mentioned: ["Prayagraj"],
    persons_named: [],
    schemes_referenced: [],
    departments_mentioned: [],
    topics: ["law-order", "crime"],
    is_law_order: true,
    risk_flag: true,
    swot_tag: "threat",
    misinformation_signal: false,
    alerted: true,
    youtube_video_id: "abc123",
    youtube_timestamp: 0,
    keywords_matched: ["प्रयागराज", "नकली नोट"],
  },
  {
    id: "art-6",
    title: "मेरठ में स्कूली शिक्षा सुधार: नई पहल की घोषणा",
    content:
      "मेरठ जिले में सरकारी स्कूलों में शिक्षा गुणवत्ता बढ़ाने के लिए नई योजना शुरू।",
    summary_english:
      "New initiative announced to improve quality of education in government schools in Meerut.",
    summary_hindi:
      "मेरठ में सरकारी स्कूलों में शिक्षा सुधार के लिए नई योजना।",
    url: "https://example.com/article/meerut-education",
    source_name: "Hindustan Meerut",
    source_type: "print",
    published_at: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    ingested_at: iso,
    language: "hi",
    sentiment: "positive",
    sentiment_score: 75,
    severity: null,
    districts_mentioned: ["Meerut"],
    persons_named: ["State Education Minister"],
    schemes_referenced: ["Samagra Shiksha"],
    departments_mentioned: [],
    topics: ["education", "governance"],
    is_law_order: false,
    risk_flag: false,
    swot_tag: "strength",
    misinformation_signal: false,
    alerted: false,
    youtube_video_id: null,
    youtube_timestamp: null,
    keywords_matched: ["मेरठ", "शिक्षा"],
  },
  {
    id: "art-7",
    title: "YouTube: यूपी सरकार की नई ई-गवर्नेंस पहल पर चर्चा",
    content:
      "यूपी सरकार की ई-गवर्नेंस और डिजिटल सेवाओं पर एक विशेष कार्यक्रम।",
    summary_english:
      "Special program on UP government's e-governance and digital services initiatives.",
    summary_hindi:
      "यूपी सरकार की ई-गवर्नेंस पहल पर विशेष चर्चा।",
    url: "https://youtube.com/watch?v=xyz789",
    source_name: "UP Government Official",
    source_type: "youtube",
    published_at: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    ingested_at: iso,
    language: "hi",
    sentiment: "positive",
    sentiment_score: 68,
    severity: null,
    districts_mentioned: ["Lucknow"],
    persons_named: ["Yogi Adityanath"],
    schemes_referenced: ["Digital India"],
    departments_mentioned: [],
    topics: ["governance", "technology"],
    is_law_order: false,
    risk_flag: false,
    swot_tag: "opportunity",
    misinformation_signal: false,
    alerted: false,
    youtube_video_id: "xyz789",
    youtube_timestamp: 120,
    keywords_matched: ["ई-गवर्नेंस"],
  },
  {
    id: "art-8",
    title: "स्कैन क्लिपिंग: अलीगढ़ में पानी की कमी पर रिपोर्ट",
    content:
      "स्थानीय अखबार से स्कैन की गई रिपोर्ट - अलीगढ़ के कई इलाकों में पानी की समस्या।",
    summary_english:
      "Scanned clipping: Report on water shortage in several areas of Aligarh district.",
    summary_hindi:
      "अलीगढ़ में पानी की कमी पर स्थानीय रिपोर्ट।",
    url: "https://example.com/upload/clipping-001",
    source_name: "Rashtriya Sahara Aligarh",
    source_type: "upload",
    published_at: new Date(now.getTime() - 48 * 60 * 60 * 1000).toISOString(),
    ingested_at: iso,
    language: "hi",
    sentiment: "negative",
    sentiment_score: 38,
    severity: "MEDIUM",
    districts_mentioned: ["Aligarh"],
    persons_named: [],
    schemes_referenced: ["Jal Jeevan Mission"],
    departments_mentioned: [],
    topics: ["water", "infrastructure"],
    is_law_order: false,
    risk_flag: false,
    swot_tag: "weakness",
    misinformation_signal: false,
    alerted: false,
    youtube_video_id: null,
    youtube_timestamp: null,
    keywords_matched: ["अलीगढ़", "पानी"],
  },
];

export const MOCK_ALERTS: AlertRecord[] = [
  {
    id: "al-1",
    article_id: "art-2",
    severity: "CRITICAL",
    channels: ["whatsapp"],
    message_body:
      "CRITICAL: Law & order concerns reported in Kanpur Nagar. Please review and coordinate with local administration.",
    sent_at: iso,
    article: MOCK_ARTICLES[1],
  },
  {
    id: "al-2",
    article_id: "art-5",
    severity: "HIGH",
    channels: ["whatsapp", "email"],
    message_body:
      "HIGH: Fake currency case in Prayagraj. Police arrest made. District administration notified.",
    sent_at: new Date(now.getTime() - 4 * 60 * 60 * 1000).toISOString(),
    article: MOCK_ARTICLES[4],
  },
  {
    id: "al-3",
    article_id: "art-2",
    severity: "CRITICAL",
    channels: ["email"],
    message_body:
      "CRITICAL: Follow-up alert – Kanpur law & order coverage trending. Monitor for escalation.",
    sent_at: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
    article: MOCK_ARTICLES[1],
  },
  {
    id: "al-4",
    article_id: "art-5",
    severity: "HIGH",
    channels: ["whatsapp"],
    message_body:
      "HIGH: Prayagraj crime story – fake notes. Ensure no communal angle in reporting.",
    sent_at: new Date(now.getTime() - 5 * 60 * 60 * 1000).toISOString(),
    article: MOCK_ARTICLES[4],
  },
];

export const MOCK_KEYWORDS: Keyword[] = [
  {
    id: "kw-1",
    term: "law & order",
    term_hindi: "कानून व्यवस्था",
    category: "law_order",
    variants: ["law and order", "कानून-व्यवस्था"],
    is_active: true,
    status: "active",
    created_at: iso,
    source_table: "incident_categories",
    source_id: "kw-1",
    entity_category: null,
    incident_group_name: "crime",
  },
  {
    id: "kw-2",
    term: "Gorakhpur development",
    term_hindi: "गोरखपुर विकास",
    category: "districts",
    variants: ["gorakhpur vikas"],
    is_active: false,
    status: "inactive",
    created_at: iso,
    source_table: "geo_districts",
    source_id: "kw-2",
    entity_category: null,
    incident_group_name: null,
  },
  {
    id: "kw-3",
    term: "Yogi Adityanath",
    term_hindi: "योगी आदित्यनाथ",
    category: "officials",
    variants: ["yogi", "cm up", "मुख्यमंत्री"],
    is_active: true,
    status: "active",
    created_at: iso,
    source_table: "entities",
    source_id: "kw-3",
    entity_category: "official",
    incident_group_name: null,
  },
  {
    id: "kw-4",
    term: "PM Awas Yojana",
    term_hindi: "पीएम आवास योजना",
    category: "schemes",
    variants: ["pmay", "housing scheme"],
    is_active: true,
    status: "active",
    created_at: iso,
    source_table: "entities",
    source_id: "kw-4",
    entity_category: "scheme",
    incident_group_name: null,
  },
  {
    id: "kw-5",
    term: "Jal Jeevan Mission",
    term_hindi: "जल जीवन मिशन",
    category: "schemes",
    variants: ["water mission", "tap water"],
    is_active: true,
    status: "active",
    created_at: iso,
    source_table: "entities",
    source_id: "kw-5",
    entity_category: "scheme",
    incident_group_name: null,
  },
  {
    id: "kw-6",
    term: "Varanasi",
    term_hindi: "वाराणसी",
    category: "districts",
    variants: ["banaras", "kashi"],
    is_active: true,
    status: "active",
    created_at: iso,
    source_table: "geo_districts",
    source_id: "kw-6",
    entity_category: null,
    incident_group_name: null,
  },
  {
    id: "kw-7",
    term: "governance",
    term_hindi: "शासन",
    category: "governance",
    variants: ["sarkar", "government"],
    is_active: false,
    status: "inactive",
    created_at: iso,
    source_table: "entities",
    source_id: "kw-7",
    entity_category: "organisation",
    incident_group_name: null,
  },
];

export const MOCK_SOURCES: Source[] = [
  {
    id: "src-1",
    name: "ABP Ganga",
    url: "https://abpganga.abplive.com",
    source_type: "tv",
    rss_url: null,
    youtube_channel_id: "UC123TV",
    is_active: true,
    last_scraped_at: iso,
    error_count: 0,
  },
  {
    id: "src-2",
    name: "Dainik Jagran Gorakhpur",
    url: "https://www.jagran.com/local/uttar-pradesh/gorakhpur-news",
    source_type: "print",
    rss_url: "https://example.com/rss/gorakhpur",
    youtube_channel_id: null,
    is_active: true,
    last_scraped_at: iso,
    error_count: 2,
  },
  {
    id: "src-3",
    name: "News18 UP Uttarakhand",
    url: "https://www.news18.com/hindi/up-uttarakhand",
    source_type: "tv",
    rss_url: null,
    youtube_channel_id: "UCNEWS18",
    is_active: true,
    last_scraped_at: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    error_count: 0,
  },
  {
    id: "src-4",
    name: "Amar Ujala Lucknow",
    url: "https://www.amarujala.com/uttar-pradesh/lucknow",
    source_type: "print",
    rss_url: "https://example.com/rss/amarujala-lucknow",
    youtube_channel_id: null,
    is_active: true,
    last_scraped_at: iso,
    error_count: 0,
  },
  {
    id: "src-5",
    name: "Dainik Bhaskar Varanasi",
    url: "https://www.bhaskar.com/local/varanasi",
    source_type: "online",
    rss_url: "https://example.com/rss/bhaskar-varanasi",
    youtube_channel_id: null,
    is_active: true,
    last_scraped_at: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
    error_count: 1,
  },
  {
    id: "src-6",
    name: "UP Government Official",
    url: "https://www.youtube.com/channel/UPGov",
    source_type: "youtube",
    rss_url: null,
    youtube_channel_id: "UCUPGov",
    is_active: true,
    last_scraped_at: iso,
    error_count: 0,
  },
  {
    id: "src-7",
    name: "Hindustan Meerut",
    url: "https://www.livehindustan.com/uttar-pradesh/meerut",
    source_type: "print",
    rss_url: "https://example.com/rss/hindustan-meerut",
    youtube_channel_id: null,
    is_active: false,
    last_scraped_at: new Date(now.getTime() - 72 * 60 * 60 * 1000).toISOString(),
    error_count: 5,
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: "rep-1",
    report_type: "daily",
    report_date: iso,
    summary_text:
      "Law & order concerns in Kanpur dominated coverage, while Gorakhpur development projects received positive local media. Lucknow health expansion and Varanasi accident also featured. Sentiment mix: positive on governance, negative on crime.",
    download_url: "https://example.com/report/daily.pdf",
    created_at: iso,
  },
  {
    id: "rep-2",
    report_type: "daily",
    report_date: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    summary_text:
      "Previous day summary: Prayagraj fake currency case triggered HIGH alert. Education initiative in Meerut covered. TV and print sources most active.",
    download_url: "https://example.com/report/daily-yesterday.pdf",
    created_at: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rep-3",
    report_type: "weekly",
    report_date: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    summary_text:
      "Weekly digest: Kanpur and Prayagraj law & order issues remained in focus. Gorakhpur and Lucknow development stories balanced coverage. District risk scores: Kanpur Nagar highest, Gorakhpur and Meerut improved.",
    download_url: "https://example.com/report/weekly.pdf",
    created_at: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rep-4",
    report_type: "monthly",
    report_date: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 7),
    summary_text:
      "Monthly overview: Governance and development themes led. Law & order alerts concentrated in Kanpur and Prayagraj. Health and education schemes received positive coverage. Entity co-occurrence: CM–Gorakhpur–PM Awas strongest link.",
    download_url: "https://example.com/report/monthly.pdf",
    created_at: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_DISTRICT_RISK: DistrictRisk[] = [
  {
    district: "Kanpur Nagar",
    district_hindi: "कानपुर नगर",
    risk_score: 85,
    article_count: 12,
    critical_count: 3,
    high_count: 4,
    dominant_sentiment: "negative",
    top_topics: ["law-order", "crime"],
    latest_headline: "कानपुर में law & order पर सवाल, विपक्ष ने जताई चिंता",
  },
  {
    district: "Prayagraj",
    district_hindi: "प्रयागराज",
    risk_score: 72,
    article_count: 8,
    critical_count: 1,
    high_count: 3,
    dominant_sentiment: "negative",
    top_topics: ["law-order", "crime"],
    latest_headline: "प्रयागराज में नकली नोट मामला: एक गिरफ्तार",
  },
  {
    district: "Gorakhpur",
    district_hindi: "गोरखपुर",
    risk_score: 35,
    article_count: 9,
    critical_count: 0,
    high_count: 1,
    dominant_sentiment: "positive",
    top_topics: ["development", "infrastructure"],
    latest_headline: "गोरखपुर में विकास कार्यों की तेज़ रफ़्तार",
  },
  {
    district: "Lucknow",
    district_hindi: "लखनऊ",
    risk_score: 28,
    article_count: 15,
    critical_count: 0,
    high_count: 0,
    dominant_sentiment: "positive",
    top_topics: ["health", "governance", "development"],
    latest_headline: "लखनऊ: स्वास्थ्य योजनाओं का विस्तार, 50 नई डिस्पेंसरी खुलेंगी",
  },
  {
    district: "Varanasi",
    district_hindi: "वाराणसी",
    risk_score: 42,
    article_count: 7,
    critical_count: 0,
    high_count: 1,
    dominant_sentiment: "neutral",
    top_topics: ["accident", "traffic"],
    latest_headline: "वाराणसी में सड़क दुर्घटना: तीन घायल",
  },
  {
    district: "Meerut",
    district_hindi: "मेरठ",
    risk_score: 22,
    article_count: 5,
    critical_count: 0,
    high_count: 0,
    dominant_sentiment: "positive",
    top_topics: ["education", "governance"],
    latest_headline: "मेरठ में स्कूली शिक्षा सुधार: नई पहल की घोषणा",
  },
  {
    district: "Aligarh",
    district_hindi: "अलीगढ़",
    risk_score: 55,
    article_count: 4,
    critical_count: 0,
    high_count: 0,
    dominant_sentiment: "negative",
    top_topics: ["water", "infrastructure"],
    latest_headline: "अलीगढ़ में पानी की कमी पर रिपोर्ट",
  },
];

const h = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
export const MOCK_SENTIMENT_TREND: SentimentTrendPoint[] = [
  { timestamp: h(0), positive: 12, negative: 5, neutral: 3 },
  { timestamp: h(1), positive: 10, negative: 6, neutral: 4 },
  { timestamp: h(2), positive: 11, negative: 5, neutral: 5 },
  { timestamp: h(3), positive: 9, negative: 7, neutral: 4 },
  { timestamp: h(4), positive: 8, negative: 8, neutral: 5 },
  { timestamp: h(5), positive: 7, negative: 9, neutral: 4 },
  { timestamp: h(6), positive: 6, negative: 7, neutral: 6 },
  { timestamp: h(12), positive: 14, negative: 4, neutral: 7 },
  { timestamp: h(18), positive: 16, negative: 3, neutral: 6 },
  { timestamp: h(24), positive: 18, negative: 5, neutral: 8 },
];

export const MOCK_TOPIC_DISTRIBUTION: TopicDistributionItem[] = [
  { topic: "law-order", count: 14 },
  { topic: "development", count: 12 },
  { topic: "governance", count: 10 },
  { topic: "health", count: 8 },
  { topic: "infrastructure", count: 7 },
  { topic: "education", count: 6 },
  { topic: "politics", count: 5 },
  { topic: "crime", count: 4 },
  { topic: "water", count: 3 },
  { topic: "technology", count: 2 },
];

export const MOCK_SOURCE_VOLUME: SourceVolumeItem[] = [
  { source_name: "ABP Ganga", source_type: "tv", count: 24 },
  { source_name: "Dainik Jagran Gorakhpur", source_type: "print", count: 18 },
  { source_name: "Amar Ujala Lucknow", source_type: "print", count: 15 },
  { source_name: "News18 UP Uttarakhand", source_type: "tv", count: 12 },
  { source_name: "Dainik Bhaskar Varanasi", source_type: "online", count: 10 },
  { source_name: "UP Government Official", source_type: "youtube", count: 8 },
  { source_name: "Hindustan Meerut", source_type: "print", count: 6 },
  { source_name: "Rashtriya Sahara Aligarh", source_type: "upload", count: 4 },
];

export const MOCK_KEYWORD_TRENDING: { keyword: string; count: number }[] = [
  { keyword: "law-order", count: 19 },
  { keyword: "development", count: 16 },
  { keyword: "governance", count: 14 },
  { keyword: "health", count: 11 },
  { keyword: "education", count: 9 },
  { keyword: "crime", count: 8 },
  { keyword: "water", count: 7 },
  { keyword: "infrastructure", count: 6 },
  { keyword: "technology", count: 5 },
  { keyword: "e-governance", count: 4 },
  { keyword: "employment", count: 10 },
  { keyword: "farmer-welfare", count: 9 },
  { keyword: "women-safety", count: 8 },
  { keyword: "road-connectivity", count: 7 },
  { keyword: "power-supply", count: 7 },
  { keyword: "sanitation", count: 6 },
  { keyword: "pollution", count: 5 },
  { keyword: "industry", count: 5 },
  { keyword: "tourism", count: 4 },
  { keyword: "budget-announcement", count: 4 },
  { keyword: "digital-services", count: 3 },
  { keyword: "youth-programs", count: 3 },
  { keyword: "forest-conservation", count: 4 },
  { keyword: "rainfall-updates", count: 3 },
  { keyword: "flood-relief", count: 5 },
  { keyword: "drought-management", count: 4 },
  { keyword: "covid-management", count: 6 },
  { keyword: "hospital-capacity", count: 5 },
  { keyword: "primary-education", count: 6 },
  { keyword: "higher-education", count: 5 },
  { keyword: "skill-development", count: 7 },
  { keyword: "startup-policy", count: 4 },
  { keyword: "investor-summit", count: 3 },
  { keyword: "smart-villages", count: 4 },
  { keyword: "metro-projects", count: 5 },
  { keyword: "rail-connectivity", count: 4 },
  { keyword: "airport-expansion", count: 3 },
  { keyword: "heritage-conservation", count: 4 },
  { keyword: "clean-river", count: 3 },
  { keyword: "solid-waste", count: 3 },
  { keyword: "traffic-management", count: 4 },
  { keyword: "cyber-crime", count: 3 },
];

export const MOCK_SEVERITY_DISTRIBUTION: Record<Severity, number> = {
  CRITICAL: 4,
  HIGH: 8,
  MEDIUM: 12,
  LOW: 18,
};

export const MOCK_ENTITY_GRAPH: EntityCooccurrenceData = {
  nodes: [
    { id: "Yogi Adityanath", label: "Yogi Adityanath", type: "politicians", count: 30 },
    { id: "Keshav Prasad Maurya", label: "Keshav Prasad Maurya", type: "politicians", count: 18 },
    { id: "Brajesh Pathak", label: "Brajesh Pathak", type: "politicians", count: 16 },
    { id: "State Education Minister", label: "State Education Minister", type: "politicians", count: 12 },
    { id: "State Health Minister", label: "State Health Minister", type: "politicians", count: 14 },
    { id: "State Home Minister", label: "State Home Minister", type: "politicians", count: 13 },
    { id: "MoS Urban Development", label: "MoS Urban Development", type: "politicians", count: 10 },
    { id: "MoS Rural Development", label: "MoS Rural Development", type: "politicians", count: 9 },
    { id: "Opposition leaders", label: "Opposition leaders", type: "politicians", count: 11 },
    { id: "District Magistrate Lucknow", label: "District Magistrate Lucknow", type: "politicians", count: 8 },
    { id: "Lucknow", label: "Lucknow", type: "districts", count: 26 },
    { id: "Kanpur Nagar", label: "Kanpur Nagar", type: "districts", count: 22 },
    { id: "Gorakhpur", label: "Gorakhpur", type: "districts", count: 20 },
    { id: "Prayagraj", label: "Prayagraj", type: "districts", count: 17 },
    { id: "Varanasi", label: "Varanasi", type: "districts", count: 18 },
    { id: "Meerut", label: "Meerut", type: "districts", count: 15 },
    { id: "Aligarh", label: "Aligarh", type: "districts", count: 14 },
    { id: "Agra", label: "Agra", type: "districts", count: 13 },
    { id: "Bareilly", label: "Bareilly", type: "districts", count: 12 },
    { id: "Jhansi", label: "Jhansi", type: "districts", count: 11 },
    { id: "Ayodhya", label: "Ayodhya", type: "districts", count: 16 },
    { id: "Noida", label: "Noida", type: "districts", count: 19 },
    { id: "Ghaziabad", label: "Ghaziabad", type: "districts", count: 18 },
    { id: "Mathura", label: "Mathura", type: "districts", count: 10 },
    { id: "Moradabad", label: "Moradabad", type: "districts", count: 9 },
    { id: "Basti", label: "Basti", type: "districts", count: 8 },
    { id: "Sitapur", label: "Sitapur", type: "districts", count: 8 },
    { id: "Barabanki", label: "Barabanki", type: "districts", count: 9 },
    { id: "Azamgarh", label: "Azamgarh", type: "districts", count: 10 },
    { id: "Saharanpur", label: "Saharanpur", type: "districts", count: 11 },
    { id: "PM Awas Yojana", label: "PM Awas Yojana", type: "schemes", count: 18 },
    { id: "Ayushman Bharat", label: "Ayushman Bharat", type: "schemes", count: 17 },
    { id: "Jal Jeevan Mission", label: "Jal Jeevan Mission", type: "schemes", count: 15 },
    { id: "Samagra Shiksha", label: "Samagra Shiksha", type: "schemes", count: 13 },
    { id: "Digital India", label: "Digital India", type: "schemes", count: 14 },
    { id: "ODOP", label: "ODOP", type: "schemes", count: 12 },
    { id: "PM Kisan", label: "PM Kisan", type: "schemes", count: 16 },
    { id: "Swachh Bharat", label: "Swachh Bharat", type: "schemes", count: 11 },
    { id: "Smart City Mission", label: "Smart City Mission", type: "schemes", count: 10 },
    { id: "CM Fellowship", label: "CM Fellowship", type: "schemes", count: 9 },
    { id: "UP Skill Mission", label: "UP Skill Mission", type: "schemes", count: 8 },
    { id: "Mission Shakti", label: "Mission Shakti", type: "schemes", count: 12 },
    { id: "PMGSY", label: "PMGSY", type: "schemes", count: 10 },
    { id: "National Health Mission", label: "National Health Mission", type: "schemes", count: 13 },
  ],
  links: [
    { source: "Yogi Adityanath", target: "Lucknow", weight: 15 },
    { source: "Yogi Adityanath", target: "Gorakhpur", weight: 14 },
    { source: "Yogi Adityanath", target: "Varanasi", weight: 11 },
    { source: "Yogi Adityanath", target: "Ayodhya", weight: 10 },
    { source: "Yogi Adityanath", target: "Kanpur Nagar", weight: 9 },
    { source: "Yogi Adityanath", target: "Noida", weight: 8 },
    { source: "Yogi Adityanath", target: "PM Awas Yojana", weight: 12 },
    { source: "Yogi Adityanath", target: "PM Kisan", weight: 11 },
    { source: "Yogi Adityanath", target: "Ayushman Bharat", weight: 9 },
    { source: "Yogi Adityanath", target: "Mission Shakti", weight: 8 },
    { source: "Yogi Adityanath", target: "Digital India", weight: 7 },
    { source: "Keshav Prasad Maurya", target: "Kanpur Nagar", weight: 8 },
    { source: "Keshav Prasad Maurya", target: "Prayagraj", weight: 7 },
    { source: "Keshav Prasad Maurya", target: "Jhansi", weight: 6 },
    { source: "Keshav Prasad Maurya", target: "PMGSY", weight: 8 },
    { source: "Keshav Prasad Maurya", target: "PM Awas Yojana", weight: 7 },
    { source: "Brajesh Pathak", target: "Lucknow", weight: 7 },
    { source: "Brajesh Pathak", target: "Varanasi", weight: 6 },
    { source: "Brajesh Pathak", target: "Ayushman Bharat", weight: 8 },
    { source: "Brajesh Pathak", target: "National Health Mission", weight: 9 },
    { source: "State Health Minister", target: "Ayushman Bharat", weight: 10 },
    { source: "State Health Minister", target: "National Health Mission", weight: 10 },
    { source: "State Health Minister", target: "Lucknow", weight: 6 },
    { source: "State Health Minister", target: "Meerut", weight: 5 },
    { source: "State Education Minister", target: "Samagra Shiksha", weight: 10 },
    { source: "State Education Minister", target: "UP Skill Mission", weight: 7 },
    { source: "State Education Minister", target: "Lucknow", weight: 6 },
    { source: "State Education Minister", target: "Barabanki", weight: 5 },
    { source: "State Home Minister", target: "Kanpur Nagar", weight: 8 },
    { source: "State Home Minister", target: "Prayagraj", weight: 8 },
    { source: "State Home Minister", target: "Moradabad", weight: 6 },
    { source: "State Home Minister", target: "Mission Shakti", weight: 7 },
    { source: "MoS Urban Development", target: "Noida", weight: 7 },
    { source: "MoS Urban Development", target: "Ghaziabad", weight: 7 },
    { source: "MoS Urban Development", target: "Smart City Mission", weight: 9 },
    { source: "MoS Urban Development", target: "Swachh Bharat", weight: 6 },
    { source: "MoS Rural Development", target: "Basti", weight: 6 },
    { source: "MoS Rural Development", target: "Sitapur", weight: 5 },
    { source: "MoS Rural Development", target: "PMGSY", weight: 7 },
    { source: "MoS Rural Development", target: "Jal Jeevan Mission", weight: 8 },
    { source: "District Magistrate Lucknow", target: "Lucknow", weight: 7 },
    { source: "District Magistrate Lucknow", target: "Digital India", weight: 5 },
    { source: "District Magistrate Lucknow", target: "Swachh Bharat", weight: 4 },
    { source: "Opposition leaders", target: "Kanpur Nagar", weight: 6 },
    { source: "Opposition leaders", target: "Prayagraj", weight: 5 },
    { source: "Opposition leaders", target: "Agra", weight: 4 },
    { source: "Opposition leaders", target: "Mission Shakti", weight: 3 },
    { source: "Lucknow", target: "Ayushman Bharat", weight: 9 },
    { source: "Lucknow", target: "Digital India", weight: 8 },
    { source: "Lucknow", target: "Smart City Mission", weight: 7 },
    { source: "Lucknow", target: "CM Fellowship", weight: 7 },
    { source: "Kanpur Nagar", target: "PM Awas Yojana", weight: 7 },
    { source: "Kanpur Nagar", target: "Mission Shakti", weight: 6 },
    { source: "Gorakhpur", target: "PM Kisan", weight: 8 },
    { source: "Gorakhpur", target: "Jal Jeevan Mission", weight: 6 },
    { source: "Varanasi", target: "Swachh Bharat", weight: 6 },
    { source: "Varanasi", target: "ODOP", weight: 7 },
    { source: "Prayagraj", target: "PMGSY", weight: 5 },
    { source: "Prayagraj", target: "Mission Shakti", weight: 5 },
    { source: "Meerut", target: "UP Skill Mission", weight: 6 },
    { source: "Meerut", target: "PM Awas Yojana", weight: 5 },
    { source: "Aligarh", target: "Jal Jeevan Mission", weight: 6 },
    { source: "Aligarh", target: "PM Kisan", weight: 4 },
    { source: "Agra", target: "ODOP", weight: 6 },
    { source: "Bareilly", target: "PM Awas Yojana", weight: 5 },
    { source: "Jhansi", target: "PMGSY", weight: 6 },
    { source: "Ayodhya", target: "PM Awas Yojana", weight: 7 },
    { source: "Ayodhya", target: "Mission Shakti", weight: 5 },
    { source: "Noida", target: "Smart City Mission", weight: 8 },
    { source: "Noida", target: "Digital India", weight: 8 },
    { source: "Ghaziabad", target: "Smart City Mission", weight: 7 },
    { source: "Mathura", target: "ODOP", weight: 5 },
    { source: "Moradabad", target: "PM Kisan", weight: 4 },
    { source: "Basti", target: "Jal Jeevan Mission", weight: 5 },
    { source: "Sitapur", target: "PM Kisan", weight: 4 },
    { source: "Barabanki", target: "Samagra Shiksha", weight: 5 },
    { source: "Azamgarh", target: "PM Awas Yojana", weight: 4 },
    { source: "Saharanpur", target: "PMGSY", weight: 5 },
    { source: "Kanpur Nagar", target: "Lucknow", weight: 4 },
    { source: "Noida", target: "Ghaziabad", weight: 5 },
    { source: "Gorakhpur", target: "Basti", weight: 4 },
    { source: "Prayagraj", target: "Varanasi", weight: 4 },
  ],
};

export const MOCK_TV_CHANNELS: TVChannel[] = [
  {
    id: "tv-1",
    name: "ABP Ganga",
    youtube_channel_id: "UC123TV",
    is_active: true,
    is_live: true,
    last_checked: iso,
    last_transcript:
      "कानपुर में हुई घटना पर विशेषज्ञों ने कहा कि पुलिस को और सख्ती दिखानी होगी…",
    today_severity: "CRITICAL",
  },
  {
    id: "tv-2",
    name: "News18 UP Uttarakhand",
    youtube_channel_id: "UCNEWS18",
    is_active: true,
    is_live: false,
    last_checked: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
    last_transcript: "आज के कार्यक्रम में देखते हैं यूपी के विकास कार्यों की ग्राउंड रिपोर्ट…",
    today_severity: "MEDIUM",
  },
  {
    id: "tv-3",
    name: "India TV UP",
    youtube_channel_id: "UCIndiaTV",
    is_active: true,
    is_live: true,
    last_checked: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
    last_transcript: "प्रयागराज में नकली नोट मामले की खबर… पुलिस ने एक आरोपी को हिरासत में लिया।",
    today_severity: "HIGH",
  },
  {
    id: "tv-4",
    name: "Zee UP UK",
    youtube_channel_id: "UCZeeUP",
    is_active: true,
    is_live: false,
    last_checked: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    last_transcript: "लखनऊ में स्वास्थ्य मंत्री ने नई डिस्पेंसरी योजना का शुभारंभ किया।",
    today_severity: null,
  },
  {
    id: "tv-5",
    name: "DD Uttar Pradesh",
    youtube_channel_id: "UCDDUP",
    is_active: true,
    is_live: false,
    last_checked: new Date(now.getTime() - 90 * 60 * 1000).toISOString(),
    last_transcript: "मुख्यमंत्री योगी आदित्यनाथ ने गोरखपुर में विकास परियोजनाओं का निरीक्षण किया।",
    today_severity: "LOW",
  },
  {
    id: "tv-6",
    name: "ETV Bharat UP",
    youtube_channel_id: "UCETVBharat",
    is_active: false,
    is_live: false,
    last_checked: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    last_transcript: null,
    today_severity: null,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "u-1",
    name: "Admin User",
    email: "admin@dipr.up.gov.in",
    role: "ADMIN",
    is_active: true,
  },
  {
    id: "u-2",
    name: "Media Analyst",
    email: "analyst@dipr.up.gov.in",
    role: "ANALYST",
    is_active: true,
  },
  {
    id: "u-3",
    name: "Viewer User",
    email: "viewer@dipr.up.gov.in",
    role: "VIEWER",
    is_active: true,
  },
];

